version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y python3-pip
      - pip3 install awscli
      - pip3 install boto3
      - wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      - unzip terraform_0.15.5_linux_amd64.zip
      - mv terraform /usr/local/bin/ 
      
  build:
    commands:
      - cd apps
      - npm install
      - zip -r app.zip *

  post_build:
    commands:
      - cd ..
      - cp apps/app.zip infra/main/apps.zip
      - sed -i 's/<SECRET_NAME>/'"$SECRET_NAME"'/g' scripts/retrieveSecret.py
      - sed -i 's/<SECRET_NAME>/'"$SECRET_NAME"'/g' scripts/updateSecret.py
      - DB_USER=$(python3 scripts/retrieveSecret.py --group db_credentials --key username)
      - DB_PASS=$(python3 scripts/retrieveSecret.py --group db_credentials --key password)
      - DB_NAME=$(python3 scripts/retrieveSecret.py --group db_credentials --key db_name)
      - sed -i 's/<DB_USER>/'"$DB_USER"'/g' infra/main/main.tf
      - sed -i 's/<DB_PASS>/'"$DB_PASS"'/g' infra/main/main.tf
      - sed -i 's/<DB_NAME>/'"$DB_NAME"'/g' infra/main/main.tf
      - cd infra/main
      - terraform init
      - terraform apply --auto-approve
      - DB_HOST=$(terraform output -raw db_host)
      - cd ../..
      - python3 scripts/updateSecret.py --group db_credentials --key db_host --value $DB_HOST

image: node:14-alpine
