name: Push to CodeCommit

on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: read 

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::905599130754:role/github-luhurfatah
        role-duration-seconds: 900
        aws-region: ap-southeast-1

    - name: Install boto3
      run: |
        python3 -m pip install --upgrade pip
        pip install boto3

    - name: Provision DynamoDB Table for Terraform
      run: |
        python3 scripts/createDynamoDB.py --name terraform_lock_main
        python3 scripts/createDynamoDB.py --name terraform_lock_support

    - name: Replace Variables in Terraform Config
      run: |
        sed -i "s|<DB_USER>|${{ secrets.DB_USER }}|g" infra/support/main.tf
        sed -i "s|<DB_PASS>|${{ secrets.DB_PASS }}|g" infra/support/main.tf
        sed -i "s|<DB_NAME>|${{ secrets.DB_NAME }}|g" infra/support/main.tf
        sed -i "s|<SECRET_NAME>|${{ secrets.SECRET_NAME }}|g" infra/support/main.tf

    - name: Deploy Support Infrastructure with Terraform
      run: |
        cd infra/support
        terraform init
        terraform apply --auto-approve
        CODE_COMMIT_URL=$(terraform output -raw repo_url)
        echo "CODE_COMMIT_URL=$CODE_COMMIT_URL" >> $GITHUB_ENV

    - name: Set up Git for CodeCommit
      run: |
        git config --global user.email "luhurfatah@gmail.com"
        git config --global user.name "luhurfatah"
        git remote add codecommit ${{ env.CODE_COMMIT_URL }}
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git push codecommit main --force
