name: Push to CodeCommit

on:
  push:
    branches:
      - main

jobs:
  push_to_codecommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    
    - name : Replace variables
      run: |
        sed -i 's/<DB_USER>/${{ secrets.DB_USER }}/g' infra/support/main.tf
        sed -i 's/<DB_PASS>/${{ secrets.DB_PASS }}/g' infra/support/main.tf
        sed -i 's/<DB_NAME>/${{ secrets.DB_NAME }}/g' infra/support/main.tf
        sed -i 's/<SECRET_NAME>/${{ secrets.SECRET_NAME }}/g' infra/support/main.tf
   
    - name: Deploy support infra
      run: |
        cd infra/support
        terraform init 
        terraform apply --auto-approve
        CODE_COMMIT_URL=$(terraform output -raw repo_url)
        echo "CODE_COMMIT_URL=$CODE_COMMIT_URL" >> $GITHUB_ENV

    - name: Set up Git
      run: |
        git config --global user.email "luhurfatah@gmail.com"
        git config --global user.name "luhurfatah"
        git remote add codecommit ${{ env.CODE_COMMIT_URL }}
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git push codecommit main --force
   
